version: '3'
services:
  pg:
    image: postgres:10.6
    container_name: "pg_dp"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
#  web:
#    build: .
#    command: gunicorn --workers 3
#              --bind 0.0.0.0:5000
#              --env DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
#              --access-logfile /tmp/ml/access.log
#              --error-logfile /tmp/ml/error.log apps.wsgi
#    env_file:
#      - .env
#    volumes:
#      - .:/code
#      - "/tmp/ml:/tmp/ml"
#    ports:
#      - "5000:5000"

volumes:
  dbdata: