# Generated by Django 2.1 on 2019-05-23 16:24

import apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kauth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=255, verbose_name='nickname')),
                ('avatar', models.CharField(blank=True, max_length=255, verbose_name='avatar')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='id type')),
                ('is_staff', models.BooleanField(default=False, verbose_name='id type')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('k8s_roles', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='kauth.KRole', verbose_name='user k8s roles')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', apps.user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserOAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_type', models.SmallIntegerField(verbose_name='third party type')),
                ('oauth_id', models.CharField(max_length=255, verbose_name='third party id')),
                ('oauth_token', models.CharField(max_length=255, verbose_name='third party token')),
                ('expires', models.IntegerField(blank=True, verbose_name='expire time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'user_oauth',
            },
        ),
    ]
