# Generated by Django 2.1 on 2019-07-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190725_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroauth',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nickname'),
        ),
    ]
