# Generated by Django 2.1 on 2019-07-25 14:58

import apps.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190725_1141'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useroauth',
            managers=[
                ('objects', apps.user.models.UserManagerOAuth()),
            ],
        ),
    ]
