# Generated by Django 2.1 on 2019-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190725_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroauth',
            name='email',
            field=models.CharField(default='email@example.com', max_length=255, verbose_name='email'),
        ),
    ]
