# Generated by Django 2.1 on 2019-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_useroauth_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroauth',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='id staff'),
        ),
        migrations.AddField(
            model_name='useroauth',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='is superuser'),
        ),
    ]
