# Generated by Django 2.1 on 2019-07-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190728_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroauth',
            name='oauth_type',
            field=models.SmallIntegerField(default=0, verbose_name='third party type'),
        ),
    ]
