# Generated by Django 2.1 on 2019-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190728_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroauth',
            name='expires',
            field=models.IntegerField(blank=True, default=1911461050, verbose_name='expire time'),
        ),
    ]
