# Generated by Django 2.1 on 2019-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190728_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroauth',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login date'),
        ),
    ]
