---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mlflow
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mlflow
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      serviceAccountName: serviceaccount-data
      containers:
      - name: mlflow
        image: docker.io/wangxisea/mlflow:1.0
        imagePullPolicy: Always
        command:
          - "mlflow"
        args:
          - "server"
          - "--backend-store-uri"
          - "/mnt/mlruns"
          - "--default-artifact-root"
          - "s3://infin-data-artifact-dev/models"
          - "--host"
          - "0.0.0.0"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
        - name: mlflow
          containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: default
  labels:
    app: mlflow
  annotations:
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: mlflow
  type: NodePort