# Generated by Django 2.1 on 2019-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_name', models.CharField(max_length=100)),
                ('pod_status', models.CharField(max_length=100)),
                ('pod_namespace', models.EmailField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
