# Generated by Django 2.1 on 2019-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='pod_namespace',
            field=models.CharField(max_length=100),
        ),
    ]
