#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: gitea-deployment
#  labels:
#    app: gitea
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: gitea
#  template:
#    metadata:
#      labels:
#        app: gitea
#    spec:
#      containers:
#      - name: gitea
#        image: gitea/gitea:latest
#        ports:
#        - containerPort: 3000
#          name: gitea
#        - containerPort: 22
#          name: git-ssh

---
kind: Service
apiVersion: v1
metadata:
  name: gitea
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
  - name: gitea-http
    port: 3000
    targetPort: gitea-http
  - name: gitea-ssh
    port: 2222
    targetPort: gitea-ssh
