# Generated by Django 2.1 on 2019-07-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krole',
            name='namespace',
            field=models.CharField(max_length=255, unique=True, verbose_name='k8s namespace name'),
        ),
    ]
